### ISSUE TITLE
state change

### ISSUE THREAD

**Issue by scigghia** [ApuliaSoftware/enhanced_helpdesk#2]
seem that in form view is not possible to change the state of the activity linked to a ticket

**Comment by OpenCode** [comment]
@scigghia

Ticket and Task states are purposely separated so the user (operator) has the freedom to choose when an activity is really closed regardless of ticket.

To change the task state you must set a project in the task so Odoo can update the related states. Now you can set manually change the activity state selecting it from the "state field".

![1](https://cloud.githubusercontent.com/assets/265697/7275381/f68d808c-e903-11e4-9e70-6e0bc7050949.png)
![2](https://cloud.githubusercontent.com/assets/265697/7275384/fa89c2fe-e903-11e4-9857-457968b2a44f.png)
